// Builds src/data/lkMap.js from src/assets/source/lk.svg  →  `npm run map:build`
// Source: Simplemaps.com Sri Lanka SVG (free for commercial use; attribution appreciated — https://simplemaps.com).
import { readFileSync, writeFileSync } from 'node:fs'

const svg = readFileSync('src/assets/source/lk.svg', 'utf8')
const featuresEnd = svg.indexOf('<g id="points"')
const feats = svg.slice(0, featuresEnd)

// English names for ISO 3166-2:LK districts (source file uses transliterations)
const NAMES = {
  LK11: 'Colombo', LK12: 'Gampaha', LK13: 'Kalutara', LK21: 'Kandy', LK22: 'Matale', LK23: 'Nuwara Eliya',
  LK31: 'Galle', LK32: 'Matara', LK33: 'Hambantota', LK41: 'Jaffna', LK42: 'Kilinochchi', LK43: 'Mannar',
  LK44: 'Vavuniya', LK45: 'Mullaitivu', LK51: 'Batticaloa', LK52: 'Ampara', LK53: 'Trincomalee',
  LK61: 'Kurunegala', LK62: 'Puttalam', LK71: 'Anuradhapura', LK72: 'Polonnaruwa', LK81: 'Badulla',
  LK82: 'Monaragala', LK91: 'Ratnapura', LK92: 'Kegalle',
}

// ── paths + bbox (file only uses M m l z) ──
let minX = 1e9, minY = 1e9, maxX = -1e9, maxY = -1e9
const districts = []
for (const m of feats.matchAll(/<path d="([^"]+)"[^>]*?id="([^"]+)"/g)) {
  const [, d, id] = m
  const t = d.match(/[MmLlZz]|-?\d*\.?\d+/g)
  let x = 0, y = 0, sx = 0, sy = 0, cmd = 'M', i = 0
  const pt = () => { minX = Math.min(minX, x); maxX = Math.max(maxX, x); minY = Math.min(minY, y); maxY = Math.max(maxY, y) }
  while (i < t.length) {
    if (/[A-Za-z]/.test(t[i])) { cmd = t[i++]; if (cmd === 'z' || cmd === 'Z') { x = sx; y = sy; continue } }
    const a = parseFloat(t[i++]), b = parseFloat(t[i++])
    if (cmd === 'M') { x = a; y = b; sx = x; sy = y; cmd = 'L' }
    else if (cmd === 'm') { x += a; y += b; sx = x; sy = y; cmd = 'l' }
    else if (cmd === 'L') { x = a; y = b }
    else { x += a; y += b }
    pt()
  }
  districts.push({ id, name: NAMES[id] || id, d })
}
// label anchor per district
for (const m of svg.matchAll(/<circle class="([^"]*)" cx="([\d.]+)" cy="([\d.]+)" id="(LK\d+)"/g)) {
  const dd = districts.find((q) => q.id === m[4]); if (dd) dd.label = [+m[2], +m[3]]
}

// ── projection fit from the file's 3 reference points: x linear in lon; y linear in Mercator(lat) ──
const pts = [...svg.slice(svg.indexOf('<g id="points"')).matchAll(/class="([\d.]+)\|([\d.]+)" cx="([\d.]+)" cy="([\d.]+)"/g)]
  .map((m) => ({ lat: +m[1], lon: +m[2], x: +m[3], y: +m[4] }))
const merc = (lat) => Math.log(Math.tan(Math.PI / 4 + (lat * Math.PI) / 360))
const fit = (u, v) => { // v = a*u + b, least squares
  const n = u.length, su = u.reduce((p, c) => p + c, 0), sv = v.reduce((p, c) => p + c, 0)
  const suu = u.reduce((p, c) => p + c * c, 0), suv = u.reduce((p, c, k) => p + c * v[k], 0)
  const a = (n * suv - su * sv) / (n * suu - su * su); return [a, (sv - a * su) / n]
}
const [ax, bx] = fit(pts.map((p) => p.lon), pts.map((p) => p.x))
const [ay, by] = fit(pts.map((p) => merc(p.lat)), pts.map((p) => p.y))
const err = pts.map((p) => [(ax * p.lon + bx - p.x).toFixed(2), (ay * merc(p.lat) + by - p.y).toFixed(2)])
console.log('fit residuals (svg units, x/y):', JSON.stringify(err))

const pad = 40
const viewBox = [minX - pad, minY - pad, maxX - minX + pad * 2, maxY - minY + pad * 2].map((n) => +n.toFixed(1))
const out = `// GENERATED by scripts/build-map.mjs from src/assets/source/lk.svg — do not edit by hand.
// Map geometry: Simplemaps.com (free for commercial use; attribution appreciated).
export const LK_MAP = ${JSON.stringify({ viewBox, fit: { ax, bx, ay, by }, districts }, null, 1)}
`
writeFileSync('src/data/lkMap.js', out)
console.log('viewBox', viewBox.join(' '), '· districts', districts.length)
